name: First Workflow
# workflow_dispatch - manually triggered by user
on: workflow_dispatch
jobs:
  # job name (custom)
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
      - name: Print goodbye
        run: echo "${{toJSON(github.event)}}"
