name: Issue Creation trigger
on: issues
jobs:
  get-event-details:
    runs-on: ubuntu-latest
    if: contains('SvitlanaKozeletska', github.event.issue.assignee.login)
    steps:
      - name: "Output event details"
        run: echo "Success"
