name: Issue Creation trigger
on: issues
jobs:
  get-event-details:
    if: ${{ !contains(github.event.issue.labels.*.name, 'JIRA sync') && github.event.issue.assignee && contains(fromJSON('["SvitlanaKozeletska"]'), github.event.issue.assignee.login) }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Get repo code'
        uses: actions/checkout@v3
      - name: 'Output event details'
        run: echo "${{toJSON(github.event.issue.assignee.login)}}"
  information:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get repo code'
        uses: actions/checkout@v3
      - name: Run custom action
        id: ticket
        uses: SvitlanaKozeletska/jira-ticket-action@v1.4
        with:
          issue: ${{ toJSON(github.event.issue) }}
      - name: Output ticket creation response
        run: |
          echo "Response: ${{ toJSON(steps.ticket.outputs.http-response) }}"

