name: Issue Creation trigger
on: issues
jobs:
  get-event-details:
    if: github.event.issue.assignee && contains(fromJSON('["SvitlanaKozeletska"]'), github.event.issue.assignee.login)
    runs-on: ubuntu-latest
    steps:
      - name: "Output event details"
        run: echo "${{toJSON(github.event.issue.assignee.login)}}"
